import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    zIndex: 999,
  },
  calendarContainer: {
    padding: 12,
    marginTop: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  legendContainer: {
    marginTop: 25,
    marginBottom: 15,
    marginHorizontal: 20,
    padding: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  legendTitle: {
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 10,
    color: '#333333',
  },
  legendItemsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 15,
    marginVertical: 5,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 8,
  },
  legendText: {
    fontSize: 14,
    color: '#555555',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 24,
    padding: 24,
    width: '92%',
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E1E1E',
    flex: 1,
  },
  todayBadge: {
    backgroundColor: '#3F51B5',
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  todayText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
  },
  eventListContainer: {
    marginBottom: 15,
  },
  eventItem: {
    padding: 14,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 12,
    marginVertical: 7,
    backgroundColor: '#FFFFFF',
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  eventTypeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  eventTypeIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 6,
  },
  eventType: {
    fontWeight: '600',
    fontSize: 12,
    color: '#666666',
  },
  eventDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eventName: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333333',
    flex: 1,
  },
  eventAmount: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  deleteButton: {
    padding: 4,
  },
  noEventsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  noEventsText: {
    textAlign: 'center',
    color: '#666',
    fontSize: 16,
    marginTop: 10,
  },
  eventSummaryContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#3F51B5',
  },
  eventSummaryTitle: {
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 10,
    color: '#333333',
  },
  eventSummaryContent: {
    gap: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  summaryLabel: {
    fontSize: 14,
    color: '#555555',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  closeButton: {
    flex: 1,
    padding: 14,
    backgroundColor: '#3F51B5',
    borderRadius: 10,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  closeButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  addButtonsContainer: {
    marginTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  addButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 14,
    borderRadius: 10,
    gap: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  addButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  
  // Record selector styles
  recordSelectorContainer: {
    flex: 1,
    maxHeight: '100%',
  },
  recordSelectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  recordSelectorTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  closeSelector: {
    padding: 5,
  },
  searchInput: {
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    padding: 12,
    marginBottom: 15,
    fontSize: 14,
  },
  recordsList: {
    maxHeight: 400,
  },
  recordsListContent: {
    paddingBottom: 10,
  },
  recordItem: {
    padding: 12,
    borderWidth: 1,
    borderColor: '#EEEEEE',
    borderRadius: 10,
    marginBottom: 8,
    backgroundColor: '#FFFFFF',
  },
  recordText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#333',
    marginBottom: 4,
  },
  recordDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  recordCategory: {
    fontSize: 12,
    color: '#757575',
    flex: 1,
  },
  recordAmount: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3F51B5',
  },
  noRecordsContainer: {
    alignItems: 'center',
    paddingVertical: 30,
  },
  noRecordsText: {
    fontSize: 16,
    color: '#666',
    marginBottom: 15,
  },
  createNewButton: {
    backgroundColor: '#3F51B5',
    padding: 14,
    borderRadius: 10,
    alignItems: 'center',
    minWidth: 200,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  createNewButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3F51B5',
    padding: 14,
    borderRadius: 10,
    marginTop: 15,
    gap: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  backButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
  
  // Monthly Stats Section Styles
  monthlyStatsContainer: {
    marginHorizontal: 16,
    marginVertical: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  monthlyStatsTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 15,
    color: '#333333',
    textAlign: 'center',
  },
  statsCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 12,
  },
  statsCard: {
    flex: 1,
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 110,
    justifyContent: 'center',
  },
  statsLabel: {
    fontSize: 12,
    marginTop: 8,
    marginBottom: 4,
    color: '#666666',
    fontWeight: '500',
    textAlign: 'center',
  },
  statsValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  upcomingContainer: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
    paddingTop: 15,
  },
  upcomingTitle: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 12,
    color: '#333333',
  },
  upcomingEvent: {
    flexDirection: 'row',
    padding: 10,
    marginBottom: 10,
    backgroundColor: '#FAFAFA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  upcomingDate: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: '#3F51B5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  upcomingDay: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  upcomingMonth: {
    fontSize: 10,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  upcomingDetail: {
    flex: 1,
    justifyContent: 'center',
  },
  upcomingName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 4,
  },
  upcomingAmount: {
    fontSize: 14,
    fontWeight: '600',
  },
  noUpcomingEvents: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    backgroundColor: '#F5F7FA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEEEEE',
  },
  noUpcomingText: {
    color: '#757575',
    fontSize: 14,
    textAlign: 'center',
  },
});

export default styles; 