import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: '#FCFCFD',
  },
  container: {
    flex: 1,
    padding: 0,
  },
  // Loading Screen
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FCFCFD',
    padding: 20,
  },
  loadingText: {
    marginTop: 20,
    fontSize: 16,
    color: '#4A5568',
    fontWeight: '500',
  },
  // Error Screen
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FCFCFD',
    padding: 40,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#E74C3C',
    marginTop: 16,
    marginBottom: 8,
  },
  errorText: {
    fontSize: 16,
    color: '#4A5568',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  retryButton: {
    backgroundColor: '#F9A825',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    boxShadow: '0px 4px 8px rgba(249, 168, 37, 0.3)',
    elevation: 4,
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  headerContainer: {
    backgroundColor: '#F9A825',
    paddingTop: 40,
    paddingBottom: 50,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    boxShadow: '0px 10px 20px rgba(22, 23, 34, 0.15)',
    elevation: 10,
    zIndex: 1,
  },
  headerContent: {
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 24,
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  profileImageWrapper: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    boxShadow: '0px 5px 10px rgba(0, 0, 0, 0.2)',
    elevation: 8,
    position: 'relative',
  },
  profileImageWrapperEditing: {
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.7)',
    boxShadow: '0px 0px 12px rgba(255, 255, 255, 0.5)',
  },
  profileImagePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(249, 168, 37, 0.2)',
  },
  profileInitials: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#F9A825',
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  cameraIconWrapper: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F9A825',
    justifyContent: 'center',
    alignItems: 'center',
    boxShadow: '0px 2px 5px rgba(22, 23, 34, 0.2)',
    elevation: 4,
  },
  cameraIconDisabled: {
    backgroundColor: '#CBD5E0',
    opacity: 0.7,
  },
  userName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  userEmail: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 16,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 50,
    gap: 8,
  },
  saveButton: {
    backgroundColor: 'rgba(0, 184, 148, 0.8)',
  },
  editButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  successMessage: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 184, 148, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 50,
    marginTop: 16,
    gap: 8,
  },
  successMessageText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#00B894',
  },
  sectionContainer: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginBottom: 24,
    borderRadius: 20,
    padding: 20,
    boxShadow: '0px 2px 10px rgba(22, 23, 34, 0.06)',
    elevation: 3,
  },
  personalInfoContainer: {
    marginTop: -30,
    paddingTop: 25,
    zIndex: 2,
    boxShadow: '0px 3px 10px rgba(0, 0, 0, 0.1)',
    elevation: 6,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#161722',
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A5568',
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  inputWrapperDisabled: {
    backgroundColor: '#F8FAFD',
    borderColor: '#E4E6EF',
    opacity: 0.9,
  },
  inputWrapperFocused: {
    borderColor: '#F9A825',
    backgroundColor: '#FFFDF8',
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 2,
  },
  datePickerWrapper: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
  },
  datePickerWebContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  datePickerWebIcon: {
    marginLeft: 16,
    marginRight: 12,
  },
  datePickerValue: {
    paddingLeft: 46,
    fontSize: 16,
    color: '#161722',
    height: 50,
    textAlignVertical: 'center',
  },
  datePickerValueEmpty: {
    color: '#A0AEC0',
  },
  textAreaWrapper: {
    backgroundColor: '#F8FAFD',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 16,
    fontSize: 16,
    color: '#161722',
  },
  inputDisabled: {
    color: '#718096',
    backgroundColor: '#F8FAFD',
  },
  textArea: {
    width: '100%',
    paddingVertical: 16,
    fontSize: 16,
    color: '#161722',
    textAlignVertical: 'top',
    minHeight: 120,
  },
  preferenceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F9',
  },
  preferenceIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(249, 168, 37, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  preferenceContent: {
    flex: 1,
  },
  preferenceLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#161722',
    marginBottom: 4,
  },
  preferenceValue: {
    fontSize: 14,
    color: '#718096',
  },
  preferenceDescription: {
    fontSize: 14,
    color: '#718096',
  },
  preferenceEditButton: {
    padding: 8,
  },
  privacyOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F9',
  },
  privacyOptionIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: 'rgba(249, 168, 37, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  privacyOptionContent: {
    flex: 1,
  },
  privacyOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#161722',
    marginBottom: 4,
  },
  privacyOptionDescription: {
    fontSize: 14,
    color: '#718096',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E74C3C',
    marginHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#E74C3C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    gap: 10,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  footerSpace: {
    height: 40,
  },
  datePickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  datePickerModalContainer: {
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E4E6EF',
  },
  datePickerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#161722',
  },
  datePicker: {
    marginBottom: 20,
  },
  datePickerConfirmButton: {
    backgroundColor: '#F9A825',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  datePickerConfirmText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  pickerContainer: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    borderRadius: 12,
    backgroundColor: '#F8FAFD',
    overflow: 'hidden',
  },
});

export default styles;