import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 16,
    backgroundColor: '#FCFCFD',
    paddingTop: 32,
    alignItems: 'center',
  },
  contentContainer: {
    width: '100%',
    maxWidth: 600,
    alignItems: 'center',
  },
  // Subtle background decorations
  gradientHeader: {
    width: '100%',
    position: 'absolute',
    top: 0,
    height: 40,
    backgroundColor: 'rgba(255, 107, 53, 0.03)',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  decorationCircle: {
    position: 'absolute',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 107, 53, 0.05)',
    top: 30,
    left: -10,
  },
  decorationDot: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(255, 107, 53, 0.12)',
    bottom: 140,
    right: 25,
  },
  // Beautiful Modern Header Container
  modernHeaderContainer: {
    position: 'relative',
    width: '100%',
    paddingTop: Platform.OS === 'ios' ? 55 : 25,
    paddingBottom: 35,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 28,
    marginHorizontal: -16,
    marginTop: -32,
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    elevation: 15,
    minWidth: '100%',
  },

  // Floating decorative elements
  floatingCircle1: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    top: -40,
    right: -30,
    zIndex: 1,
  },
  floatingCircle2: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    bottom: -20,
    left: -20,
    zIndex: 1,
  },
  floatingCircle3: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    top: 20,
    left: 20,
    zIndex: 1,
  },
  geometricShape: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    top: 40,
    right: 30,
    transform: [{ rotate: '45deg' }],
    borderRadius: 8,
    zIndex: 1,
  },

  // Header content
  headerContent: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 10,
    width: '100%',
    paddingHorizontal: 10,
  },

  // Beautiful shield with glow effect
  shieldContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  shieldGlow: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    top: -5,
    left: -5,
    zIndex: 1,
  },
  shieldBackground: {
    width: 100,
    height: 100,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 2,
  },

  // Text section
  textSection: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 15,
  },
  modernTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    width: '100%',
    minWidth: 280,
  },
  modernUnderline: {
    height: 3,
    width: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  // Enhanced Security Cards Container
  securityCardsContainer: {
    width: '100%',
    marginBottom: 24,
  },
  securityCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.2)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  securityCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  securityIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  securityCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.2,
    flex: 1,
  },
  statusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    color: '#00B894',
    fontWeight: '600',
    marginLeft: 8,
  },
  securityCardDescription: {
    fontSize: 14,
    color: '#718096',
    lineHeight: 20,
  },

  // Device Information Section
  deviceSection: {
    width: '100%',
    marginBottom: 24,
  },
  deviceInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.2)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  deviceCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  deviceIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  deviceInfoTextContainer: {
    flex: 1,
  },
  deviceCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.2,
  },
  deviceCardSubtitle: {
    fontSize: 14,
    color: '#718096',
    marginTop: 2,
  },
  deviceDetails: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 152, 0, 0.1)',
  },
  deviceDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  deviceDetailLabel: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '600',
  },
  deviceDetailValue: {
    fontSize: 14,
    color: '#2D3748',
    fontWeight: '500',
  },
  actionButtonsContainer: {
    width: '100%',
    marginTop: 8,
  },
  
  // Enhanced Primary Action Button (Change Password)
  primaryActionButton: {
    backgroundColor: '#FF9800',
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  primaryButtonIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  primaryButtonTextContainer: {
    flex: 1,
  },
  primaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  primaryButtonSubtext: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },

  // Enhanced Secondary Action Button (Change Email)
  secondaryActionButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 152, 0, 0.3)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  secondaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  secondaryButtonIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  secondaryButtonTextContainer: {
    flex: 1,
  },
  secondaryButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.2,
  },
  secondaryButtonSubtext: {
    fontSize: 14,
    color: '#718096',
    marginTop: 2,
  },

  // Device Management Button
  deviceManagementButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 152, 0, 0.3)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  deviceManagementContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
  },
  deviceManagementIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  deviceManagementTextContainer: {
    flex: 1,
  },
  deviceManagementText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.2,
  },
  deviceManagementSubtext: {
    fontSize: 14,
    color: '#718096',
    marginTop: 2,
  },

  // Security Tips Card
  tipsCard: {
    backgroundColor: '#FFFBF5',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.2)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  tipsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  tipsIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 152, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  tipsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.2,
  },
  tipText: {
    fontSize: 14,
    color: '#4A5568',
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContainer: {
    width: '100%',
    maxWidth: 400,
    padding: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.25,
    shadowRadius: 30,
    elevation: 20,
    overflow: 'hidden',
  },
  modalHeaderContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
    marginBottom: 0,
  },
  modalHeader: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: -0.3,
  },

  modalContent: {
    padding: 24,
    paddingTop: 20,
  },
  inputContainer: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
    letterSpacing: 0.1,
  },
  input: {
    padding: 16,
    marginBottom: 5,
    width: '100%',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    fontSize: 16,
    color: '#111827',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  focusedInput: {
    borderColor: '#FF9800',
    backgroundColor: '#FFFBF5',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  inputHelpText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 4,
    marginLeft: 4,
  },
  modalButtons: {
    padding: 24,
    paddingTop: 8,
    gap: 12,
  },
  submitButton: {
    backgroundColor: '#FF9800',
    paddingVertical: 16,
    alignItems: 'center',
    borderRadius: 14,
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  submitIcon: {
    marginRight: 8,
  },
  goBackButton: {
    backgroundColor: '#F3F4F6',
    paddingVertical: 16,
    alignItems: 'center',
    borderRadius: 14,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  goBackButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    letterSpacing: 0.1,
  },
  currentEmailContainer: {
    marginBottom: 20,
    padding: 16,
    backgroundColor: '#FFF7ED',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FED7AA',
    alignItems: 'center',
  },
  currentEmailLabel: {
    fontSize: 14,
    color: '#C2410C',
    fontWeight: '600',
    letterSpacing: 0.1,
    marginBottom: 4,
  },
  currentEmailValue: {
    fontSize: 15,
    color: '#EA580C',
    fontWeight: '700',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#E4E6EF',
    width: '100%',
    marginVertical: 24,
  },

  // Devices Modal Styles
  devicesModalContainer: {
    flex: 1,
    width: '95%',
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    shadowColor: '#161722',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 16,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.4)',
    maxWidth: 600,
    minHeight: 400,
  },
  devicesModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E4E6EF',
  },
  devicesModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#161722',
    letterSpacing: -0.6,
  },
  closeIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F3F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  
  // Tabs Styles
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginHorizontal: 4,
    borderRadius: 12,
    backgroundColor: '#F1F3F9',
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
  },
  activeTab: {
    backgroundColor: '#FF9800',
    borderColor: '#FF9800',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  tabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A5568',
    marginLeft: 6,
  },
  activeTabText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },

  // Devices List Styles
  devicesListContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 24,
    minHeight: 200,
  },
  deviceItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.12)',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  
  // New clean layout structure
  deviceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  deviceIcon: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  deviceTitleSection: {
    flex: 1,
  },
  deviceName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2D3748',
    lineHeight: 22,
    marginBottom: 4,
  },
  deviceStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    alignSelf: 'flex-start',
    flexShrink: 0,
    minWidth: 80,
  },
  authorizedBadge: {
    backgroundColor: '#E8F5E8',
    borderWidth: 1,
    borderColor: '#4CAF50',
  },
  blockedBadge: {
    backgroundColor: '#FFEBEE',
    borderWidth: 1,
    borderColor: '#F44336',
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  authorizedBadgeText: {
    color: '#2E7D32',
  },
  blockedBadgeText: {
    color: '#C62828',
  },
  deviceModel: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  
  // Device details section
  deviceDetailsSection: {
    marginBottom: 16,
  },
  deviceDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingVertical: 2,
  },
  deviceDetailIcon: {
    width: 18,
    marginRight: 10,
  },
  deviceDetailText: {
    fontSize: 13,
    color: '#718096',
    fontWeight: '500',
    flex: 1,
  },
  
  // Action section
  deviceActionSection: {
    borderTopWidth: 1,
    borderTopColor: '#F1F3F4',
    paddingTop: 16,
    alignItems: 'center',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    minWidth: 140,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  authorizeButton: {
    backgroundColor: '#4CAF50',
  },
  blockDeviceButton: {
    backgroundColor: '#F44336',
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginLeft: 6,
    letterSpacing: 0.3,
  },
  
  // Empty States
  emptyDevicesContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyDevicesText: {
    fontSize: 16,
    color: '#718096',
    marginTop: 12,
    textAlign: 'center',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    fontSize: 16,
    color: '#718096',
  },
});

export default styles;