import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    paddingHorizontal: 22,
    paddingVertical: 32,
    alignItems: 'center',
  },
  header: {
    fontSize: 27,
    fontWeight: 'bold',
    color: '#F57C00',
    marginBottom: 22,
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: 'rgba(255, 183, 77, 0.13)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  icon: {
    marginBottom: 18,
  },
  actionButton: {
    backgroundColor: '#FFA726',
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    marginVertical: 10,
    width: '100%',
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  actionButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  tipsSection: {
    marginTop: 20,
    padding: 18,
    backgroundColor: '#FFF',
    borderRadius: 14,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 5,
    elevation: 3,
    width: '100%',
  },
  tipText: {
    fontSize: 14,
    color: '#555',
    marginBottom: 10,
    lineHeight: 20,
    textAlign: 'left',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '92%',
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 24,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    elevation: 6,
  },
  modalHeader: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#F57C00',
    marginBottom: 18,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#FFCC80',
    borderRadius: 12,
    padding: 13,
    marginBottom: 15,
    fontSize: 16,
    color: '#333',
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  submitButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  submitButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  goBackButton: {
    backgroundColor: '#FF9800',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 15,
    width: '100%',
  },
  goBackButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  currentEmailText: {
    fontSize: 14,
    color: '#333',
    marginBottom: 10,
    textAlign: 'center',
  },
});

export default styles;