import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 24,
    backgroundColor: '#FCFCFD',
    paddingTop: 32,
  },
  header: {
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 28,
    textAlign: 'center',
    color: '#161722',
    letterSpacing: -0.8,
  },
  icon: {
    marginBottom: 24,
    alignSelf: 'center',
    opacity: 0.9,
  },
  tipsSection: {
    marginTop: 24,
    marginBottom: 28,
    padding: 24,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 8,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.7)',
  },
  tipText: {
    fontSize: 15,
    marginBottom: 14,
    textAlign: 'left',
    color: '#4A5568',
    lineHeight: 22,
    letterSpacing: 0.1,
  },
  actionButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingVertical: 20,
    paddingHorizontal: 26,
    marginVertical: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
  },
  actionButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#161722',
    marginLeft: 16,
    letterSpacing: 0.1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(22, 23, 34, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(8px)',
  },
  modalContainer: {
    width: '92%',
    padding: 32,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    shadowColor: '#161722',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 16,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.4)',
  },
  modalHeader: {
    fontSize: 26,
    fontWeight: '700',
    marginBottom: 30,
    textAlign: 'center',
    color: '#161722',
    letterSpacing: -0.6,
  },
  input: {
    padding: 20,
    marginBottom: 20,
    width: '100%',
    backgroundColor: '#FCFCFD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    fontSize: 16,
    color: '#161722',
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 1,
  },
  submitButton: {
    backgroundColor: '#F9A825',
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 28,
    borderRadius: 16,
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  goBackButton: {
    backgroundColor: '#F1F3F9',
    paddingVertical: 18,
    alignItems: 'center',
    marginTop: 16,
    borderRadius: 16,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
  },
  goBackButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#4A5568',
    letterSpacing: 0.2,
  },
  currentEmailText: {
    fontSize: 16,
    marginBottom: 24,
    textAlign: 'center',
    padding: 16,
    backgroundColor: '#F1F3F9',
    borderRadius: 16,
    color: '#4A5568',
    fontWeight: '500',
    letterSpacing: 0.2,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
  },
  buttonIcon: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(249, 168, 37, 0.15)',
    borderRadius: 12,
    marginRight: 16,
  },
});

export default styles;