import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: '100%',
    backgroundColor: '#FAFAFA',
    padding: 24,
    justifyContent: 'center',
    paddingBottom: 80,
  },
  icon: {
    marginBottom: 18,
    alignSelf: 'center',
  },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#F57C00',
    marginBottom: 26,
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: 'rgba(255, 183, 77, 0.13)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  content: {
    fontSize: 16,
    color: '#666',
    marginBottom: 22,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#FFCC80',
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    fontSize: 16,
    color: '#333',
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  textArea: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#FFCC80',
    borderRadius: 14,
    padding: 16,
    fontSize: 16,
    color: '#333',
    height: 180,
    textAlignVertical: 'top',
    marginBottom: 20,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  submitButton: {
    backgroundColor: '#FFA726',
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    width: '100%',
    marginBottom: 18,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  submitButtonText: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  faqButton: {
    backgroundColor: '#FFB74D',
    paddingVertical: 13,
    borderRadius: 14,
    alignItems: 'center',
    width: '100%',
    marginBottom: 18,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  faqButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '92%',
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 24,
    shadowColor: '#FFA726',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.13,
    shadowRadius: 8,
    elevation: 6,
  },
  modalHeader: {
    fontSize: 21,
    fontWeight: 'bold',
    color: '#F57C00',
    marginBottom: 18,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  faqScrollView: {
    maxHeight: 300,
    marginBottom: 15,
  },
  faqItem: {
    marginBottom: 15,
  },
  faqTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FFECB3',
  },
  faqQuestion: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F57C00',
  },
  faqAnswer: {
    fontSize: 14,
    color: '#333',
    marginTop: 5,
    lineHeight: 20,
  },
  closeButton: {
    backgroundColor: '#FFA726',
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  closeButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
});

export default styles;