import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const cardWidth = width * 0.88;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    minHeight: '100%',
    padding: 24,
    backgroundColor: '#FCFCFD',
    paddingTop: 32,
    alignItems: 'center',
  },
  contentContainer: {
    width: '100%',
    maxWidth: 600,
    alignItems: 'center',
  },
  gradientHeader: {
    width: '100%',
    position: 'absolute',
    top: 0,
    height: 180,
    backgroundColor: 'rgba(249, 168, 37, 0.08)',
    borderBottomLeftRadius: 100,
    borderBottomRightRadius: 30,
  },
  decorationCircle: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(249, 168, 37, 0.12)',
    top: -50,
    right: -50,
  },
  decorationDot: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(249, 168, 37, 0.2)',
    bottom: 100,
    left: 30,
  },
  icon: {
    marginBottom: 16,
    alignSelf: 'center',
    opacity: 0.9,
  },
  iconBackground: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(249, 168, 37, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  header: {
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
    color: '#161722',
    letterSpacing: -0.8,
  },
  content: {
    fontSize: 16,
    marginBottom: 32,
    textAlign: 'center',
    color: '#4A5568',
    lineHeight: 24,
    paddingHorizontal: 24,
    letterSpacing: 0.1,
    maxWidth: 500,
  },
  formCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.4)',
  },
  inputContainer: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3748',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  input: {
    marginBottom: 5,
    padding: 20,
    width: '100%',
    backgroundColor: '#F8FAFD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    fontSize: 16,
    color: '#161722',
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 1,
  },
  textArea: {
    padding: 20,
    height: 170,
    textAlignVertical: 'top',
    marginBottom: 5,
    width: '100%',
    backgroundColor: '#F8FAFD',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E4E6EF',
    fontSize: 16,
    color: '#161722',
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 1,
  },
  focusedInput: {
    borderColor: '#F9A825',
    backgroundColor: '#FFFDF8',
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  inputHelpText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 4,
    marginLeft: 4,
  },
  buttonContainer: {
    width: '100%',
    marginTop: 10,
  },
  submitButton: {
    backgroundColor: '#F9A825',
    padding: 18,
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
    borderRadius: 16,
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: '#CBD5E0',
    shadowColor: '#CBD5E0',
    shadowOpacity: 0.15,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  submitIcon: {
    marginRight: 10,
  },
  faqButtonContainer: {
    width: '100%',
  },
  faqButton: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#7B61FF',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
  },
  faqButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#161722',
    marginLeft: 12,
    letterSpacing: 0.1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(22, 23, 34, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '92%',
    padding: 32,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    shadowColor: '#161722',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 28,
    elevation: 16,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.4)',
    maxWidth: 550,
  },
  modalHeader: {
    fontSize: 26,
    fontWeight: '700',
    marginBottom: 24,
    textAlign: 'center',
    color: '#161722',
    letterSpacing: -0.6,
  },
  modalHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E4E6EF',
    paddingBottom: 16,
  },
  closeIcon: {
    padding: 8,
  },
  faqScrollView: {
    maxHeight: 420,
    marginBottom: 24,
  },
  faqItem: {
    marginBottom: 18,
    backgroundColor: '#F8FAFD',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.7)',
  },
  faqTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
  },
  faqQuestion: {
    fontSize: 17,
    fontWeight: '600',
    color: '#161722',
    flex: 1,
    paddingRight: 16,
    letterSpacing: 0.1,
  },
  faqAnswer: {
    fontSize: 16,
    marginTop: 0,
    padding: 20,
    backgroundColor: 'rgba(249, 168, 37, 0.08)',
    color: '#4A5568',
    lineHeight: 24,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    letterSpacing: 0.1,
  },
  closeButton: {
    backgroundColor: '#F1F3F9',
    padding: 18,
    alignItems: 'center',
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(228, 230, 239, 0.6)',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  closeButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#4A5568',
    letterSpacing: 0.2,
  },
  activeFaqItem: {
    borderColor: '#F9A825',
    shadowColor: '#F9A825',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  divider: {
    height: 1,
    backgroundColor: '#E4E6EF',
    width: '100%',
    marginVertical: 24,
  },
  supportInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  supportInfoText: {
    fontSize: 15,
    marginLeft: 10,
    color: '#4A5568',
  },
  supportInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(249, 168, 37, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  supportInfoContainer: {
    marginTop: 20,
    marginBottom: 8,
    width: '100%',
  },
  supportInfoTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D3748',
    marginBottom: 16,
  }
});

export default styles;