import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');
const cardWidth = width * 0.88;

const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  contentContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#FCFCFD',
    paddingHorizontal: 20,
  },
  gradientHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 80,
    backgroundColor: 'rgba(255, 152, 0, 0.05)',
    zIndex: -1,
  },
  decorationCircle: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 152, 0, 0.08)',
    top: 220,
    right: 30,
    zIndex: -1,
  },
  decorationDot: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    bottom: 150,
    left: 40,
    zIndex: -1,
  },
  // Beautiful Modern Header Container
  modernHeaderContainer: {
    position: 'relative',
    width: '100%',
    paddingTop: Platform.OS === 'ios' ? 55 : 25,
    paddingBottom: 35,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    marginBottom: 28,
    marginHorizontal: -20,
    shadowColor: '#FF6B35',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 24,
    elevation: 15,
    minWidth: '100%',
  },

  // Floating decorative elements
  floatingCircle1: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    top: -40,
    right: -30,
    zIndex: 1,
  },
  floatingCircle2: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    bottom: -20,
    left: -20,
    zIndex: 1,
  },
  floatingCircle3: {
    position: 'absolute',
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    top: 20,
    left: 20,
    zIndex: 1,
  },
  geometricShape: {
    position: 'absolute',
    width: 40,
    height: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    top: 40,
    right: 30,
    transform: [{ rotate: '45deg' }],
    borderRadius: 8,
    zIndex: 1,
  },

  // Header content
  headerContent: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 10,
    width: '100%',
    paddingHorizontal: 10,
  },

  // Beautiful headset icon with glow effect
  shieldContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  shieldGlow: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    top: -5,
    left: -5,
    zIndex: 1,
  },
  shieldBackground: {
    width: 100,
    height: 100,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: 'rgba(0, 0, 0, 0.15)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 2,
  },

  // Text section
  textSection: {
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 15,
  },
  modernTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    width: '100%',
    minWidth: 280,
  },
  modernUnderline: {
    height: 3,
    width: 50,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 2,
    elevation: 2,
  },
  icon: {
    marginBottom: 16,
    alignSelf: 'center',
    opacity: 0.9,
  },
  iconBackground: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(249, 168, 37, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  header: {
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
    color: '#161722',
    letterSpacing: -0.8,
  },
  content: {
    fontSize: 16,
    marginBottom: 32,
    textAlign: 'center',
    color: '#4A5568',
    lineHeight: 24,
    paddingHorizontal: 24,
    letterSpacing: 0.1,
    maxWidth: 500,
  },
  formCard: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.1)',
  },
  inputContainer: {
    marginBottom: 20,
    width: '100%',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3748',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  input: {
    marginBottom: 5,
    padding: 18,
    width: '100%',
    backgroundColor: '#F7F9FC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    fontSize: 16,
    color: '#2D3748',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  textArea: {
    padding: 18,
    height: 140,
    textAlignVertical: 'top',
    marginBottom: 5,
    width: '100%',
    backgroundColor: '#F7F9FC',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    fontSize: 16,
    color: '#2D3748',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  focusedInput: {
    borderColor: '#FF9800',
    backgroundColor: '#FFF8F1',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  inputHelpText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 4,
    marginLeft: 4,
  },
  buttonContainer: {
    width: '100%',
    marginTop: 10,
  },
  submitButton: {
    backgroundColor: '#FF9800',
    padding: 18,
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
    borderRadius: 14,
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  submitButtonDisabled: {
    backgroundColor: '#CBD5E0',
    shadowColor: '#CBD5E0',
    shadowOpacity: 0.15,
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.4,
  },
  submitIcon: {
    marginRight: 10,
  },
  faqButtonContainer: {
    width: '100%',
  },
  faqButton: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.15)',
  },
  faqButtonText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#161722',
    marginLeft: 12,
    letterSpacing: 0.1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '90%',
    maxHeight: '80%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  faqScrollView: {
    maxHeight: 400,
  },
  newModalHeader: {
    position: 'relative',
    backgroundColor: '#FF9800',
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  headerGradientEffect: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'linear-gradient(135deg, #FF9800 0%, #FF7043 100%)',
    opacity: 0.9,
  },
  headerIconSection: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 2,
  },
  newIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  headerTextSection: {
    flex: 1,
  },
  newModalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  newModalSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
  },
  newFaqScrollView: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  faqGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 20,
    justifyContent: 'space-between',
    minHeight: 400,
    backgroundColor: '#F8F9FA',
  },
  faqGridItem: {
    width: '47%',
    marginBottom: 16,
    flexShrink: 0,
  },
  faqCardContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 152, 0, 0.1)',
    position: 'relative',
    minHeight: 120,
    flex: 1,
  },
  faqIconBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  faqCardText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#2D3748',
    lineHeight: 18,
    letterSpacing: 0.1,
    marginBottom: 8,
    paddingRight: 35,
    flex: 1,
  },
  faqCardNumber: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FF9800',
    justifyContent: 'center',
    alignItems: 'center',
  },
  faqCardNumberText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  newModalActions: {
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.05)',
  },
  newCloseButton: {
    backgroundColor: '#FF9800',
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  newCloseButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  modalHeaderContainer: {
    backgroundColor: 'rgba(255, 152, 0, 0.05)',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 152, 0, 0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  modalTitleSection: {
    flex: 1,
  },
  modalHeader: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  closeIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(113, 128, 150, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  faqScrollView: {
    flex: 1,
    paddingTop: 16,
  },
  faqContainer: {
    paddingHorizontal: 24,
    paddingBottom: 20,
  },
  faqItem: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingVertical: 15,
  },
  faqTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  faqNumberContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 152, 0, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  faqNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FF9800',
  },
  faqQuestion: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    flex: 1,
  },
  faqChevronContainer: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 152, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  faqChevronExpanded: {
    backgroundColor: '#FF9800',
  },
  faqAnswerContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 152, 0, 0.05)',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 152, 0, 0.1)',
  },
  faqAnswerIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 152, 0, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  faqAnswer: {
    fontSize: 14,
    color: '#666',
    marginTop: 10,
    lineHeight: 20,
  },
  modalFooter: {
    backgroundColor: 'rgba(255, 152, 0, 0.05)',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 2,
    borderTopColor: 'rgba(255, 152, 0, 0.1)',
  },
  closeButton: {
    backgroundColor: '#FF9800',
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  closeButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  activeFaqItem: {
    borderColor: '#FF9800',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  divider: {
    height: 1,
    backgroundColor: '#E4E6EF',
    width: '100%',
    marginVertical: 24,
  },
  supportInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  supportInfoText: {
    fontSize: 15,
    marginLeft: 10,
    color: '#4A5568',
  },
  supportInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 152, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  supportInfoContainer: {
    marginTop: 20,
    marginBottom: 8,
    width: '100%',
  },
  supportInfoTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D3748',
    marginBottom: 16,
  }
});

export default styles;