import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 0,
  },
  chartContainer: {
    width: '100%',
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: 'transparent',
  },
  expenseItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#FFCDD2',
    borderLeftWidth: 4,
    borderLeftColor: '#F44336',
  },
  expenseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  expenseTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#C62828',
    letterSpacing: 0.3,
  },
  expenseDetails: {
    fontSize: 15,
    color: '#F44336',
    letterSpacing: 0.2,
    fontWeight: '600',
  },
  actionButton: {
    padding: 5,
    backgroundColor: '#F7FAFC',
    borderRadius: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 28,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 20,
    borderWidth: 2,
    borderColor: '#FFCDD2',
    maxHeight: '90%',
  },
  modalHeader: {
    fontSize: 24,
    fontWeight: '700',
    color: '#F44336',
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(244,67,54,0.1)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#C62828',
    marginBottom: 8,
    marginTop: 4,
    letterSpacing: 0.3,
  },
  modalInput: {
    borderWidth: 2,
    borderColor: '#FFCDD2',
    borderRadius: 16,
    padding: 16,
    marginBottom: 18,
    backgroundColor: '#FFFFFF',
    fontSize: 16,
    color: '#C62828',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
    fontWeight: '500',
  },
  picker: {
    borderWidth: 2,
    borderColor: '#FFCDD2',
    borderRadius: 16,
    padding: 16,
    marginBottom: 18,
    backgroundColor: '#FFFFFF',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 16,
  },
  closeButton: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#E0E0E0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 2,
    borderColor: '#E0E0E0',
  },
  closeButtonText: {
    color: '#616161',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 8,
  },
  saveButton: {
    flex: 1,
    backgroundColor: '#F44336',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    shadowColor: '#D32F2F',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 2,
    borderColor: '#D32F2F',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 0.5,
    marginLeft: 8,
    textShadowColor: 'rgba(0,0,0,0.2)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
  },
  actionButtonEdit: {
    padding: 10,
    backgroundColor: '#FF9800',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF9800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  actionButtonDelete: {
    padding: 10,
    backgroundColor: '#F44336',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  priorityIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  priorityMinima: {
    backgroundColor: '#FFC107',
  },
  priorityBaixa: {
    backgroundColor: '#FF9800',
  },
  priorityMedia: {
    backgroundColor: '#FF5722',
  },
  priorityAlta: {
    backgroundColor: '#F44336',
  },
  priorityMaxima: {
    backgroundColor: '#D32F2F',
  },
  categoryTag: {
    backgroundColor: '#FFCDD2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginRight: 8,
  },
  categoryText: {
    color: '#C62828',
    fontSize: 12,
    fontWeight: '600',
  },
  frequencyTag: {
    backgroundColor: '#E3F2FD',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  frequencyText: {
    color: '#2196F3',
    fontSize: 12,
    fontWeight: '600',
  },
  categoriesList: {
    maxHeight: 200,
    marginBottom: 16,
  },
  categoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  categoryItemText: {
    fontSize: 16,
    color: '#C62828',
    fontWeight: '500',
  },
  categoryActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 12,
  },
  deleteModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#F44336',
    letterSpacing: 0.5,
  },
  deleteModalText: {
    fontSize: 16,
    color: '#C62828',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.3,
  },
  deleteModalSubtext: {
    fontSize: 14,
    color: '#E57373',
    textAlign: 'center',
    marginBottom: 24,
    letterSpacing: 0.2,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F44336',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFCDD2',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  cancelButtonText: {
    color: '#C62828',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  filterInfoContainer: {
    backgroundColor: '#FFFFFF',
    padding: 10,
    borderRadius: 12,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#F44336',
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterInfoText: {
    color: '#F44336',
    fontSize: 13,
    fontWeight: '500',
  },
  modalScrollView: {
    maxHeight: 400,
    paddingRight: 4,
  },
  modalExpenseItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#FFCDD2',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  filterButtonText: {
    color: '#F44336',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 8,
  },
  clearFilterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F44336',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  clearFilterButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 12,
    marginLeft: 6,
  },
  categoryFilterItem: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    margin: 6,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '45%',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  categoryFilterItemSelected: {
    backgroundColor: '#FFEBEE',
    borderColor: '#F44336',
    borderWidth: 2,
  },
  categoryFilterText: {
    color: '#C62828',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  categoryFilterTextSelected: {
    color: '#C62828',
    fontWeight: '700',
  },
  categoryFilterRow: {
    justifyContent: 'space-between',
  },
  filterSection: {
    marginBottom: 16,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  filterHeaderText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#E57373',
  },
  categoryList: {
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  categoryChip: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    marginRight: 10,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  categoryChipSelected: {
    backgroundColor: '#FFEBEE',
    borderColor: '#F44336',
    borderWidth: 2,
  },
  categoryChipText: {
    color: '#C62828',
    fontSize: 13,
    fontWeight: '600',
  },
  categoryChipTextSelected: {
    color: '#C62828',
    fontWeight: '700',
  },
  categoryChipIndicator: {
    backgroundColor: '#F44336',
    width: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  manageButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#F44336',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{scale: 0.98}],
  },
  manageButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  manageButtonIcon: {
    backgroundColor: '#F44336',
    borderRadius: 20,
    padding: 8,
    marginRight: 10,
    shadowColor: '#D32F2F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
  },
  manageButtonText: {
    color: '#D32F2F',
    fontSize: 18,
    fontWeight: '700',
  },
  manageButtonSubtext: {
    color: '#F44336',
    fontSize: 12,
    fontStyle: 'italic',
  },
  manageModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  manageModalContainer: {
    width: '90%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 15,
    borderWidth: 2,
    borderColor: '#FFCDD2',
    maxHeight: '80%',
  },
  manageModalHeader: {
    fontSize: 20,
    fontWeight: '700',
    color: '#F44336',
    marginBottom: 20,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  manageTabContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFEBEE',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  manageTab: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  manageTabActive: {
    backgroundColor: '#F44336',
    shadowColor: '#D32F2F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },
  manageTabText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#D32F2F',
  },
  manageTabTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  manageSection: {
    flex: 1,
  },
  manageSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#C62828',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  manageItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFEBEE',
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#FFCDD2',
  },
  manageItemText: {
    fontSize: 14,
    color: '#D32F2F',
    fontWeight: '500',
    flex: 1,
  },
  manageItemActions: {
    flexDirection: 'row',
    gap: 8,
  },
  manageActionButton: {
    padding: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageEditButton: {
    backgroundColor: '#FF9800',
  },
  manageDeleteButton: {
    backgroundColor: '#F44336',
  },
  addItemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F44336',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    marginTop: 8,
  },
  addItemButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 6,
  },
  manageModalButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  manageCloseButton: {
    backgroundColor: '#F44336',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    shadowColor: '#D32F2F',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  manageCloseButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  manageScrollView: {
    maxHeight: 200,
  },
  // Skeleton loading styles
  skeletonContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  skeletonChart: {
    height: 180,
    backgroundColor: '#FFEBEE',
    borderRadius: 20,
    marginBottom: 16,
    overflow: 'hidden',
  },
  skeletonItem: {
    backgroundColor: '#FFEBEE',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    height: 120,
  },
  skeletonShimmer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  // Manage button styles aligned with add button
  manageItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#F44336',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{scale: 0.98}],
  },
  manageButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#F44336',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#F44336',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{scale: 0.98}],
  },
});

export default styles;
