import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    padding: 20,
  },
  listWrapper: {
    flex: 1,
    marginTop: 10,
  },
  header: {
    fontSize: 32,
    fontWeight: '800',
    color: '#333333',
    marginBottom: 28,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  addButton: {
    backgroundColor: '#FFB74D',
    padding: 18,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 24,
    elevation: 4,
    shadowColor: '#FFB74D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  listContainer: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  goalItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    borderLeftWidth: 6,
    borderLeftColor: '#FFB74D',
  },
  goalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  goalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
    flex: 1,
    marginRight: 12,
    letterSpacing: 0.3,
  },
  goalAmount: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFB74D',
    textAlign: 'right',
  },
  goalDeadline: {
    fontSize: 15,
    color: '#666666',
    fontStyle: 'italic',
    marginTop: 4,
  },
  goalSaving: {
    fontSize: 16,
    color: '#666666',
    fontWeight: '500',
  },
  goalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderRadius: 16,
    gap: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  editButton: {
    backgroundColor: '#FFB74D',
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF6B6B',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  statusContainer: {
    flexDirection: 'column',
    marginTop: 28,
    padding: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusIcon: {
    marginRight: 14,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
  },
  statusText: {
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 12,
  },
  originalSettingsText: {
    fontSize: 15,
    color: '#666666',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#DFE6E9',
    fontStyle: 'italic',
    lineHeight: 22,
  },
  originalSettingsValue: {
    fontSize: 15,
    color: '#333333',
    fontWeight: '600',
    marginTop: 6,
  },
  statusSuccess: {
    color: '#FFB74D',
  },
  statusWarning: {
    color: '#FFA726',
  },
  statusError: {
    color: '#FF6B6B',
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  emptyStateText: {
    fontSize: 20,
    color: '#666666',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 28,
    fontWeight: '500',
  },
  goalStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 14,
    color: '#7F8C8D',
    textAlign: 'center',
  },
  alertContainer: {
    position: 'absolute',
    top: 20,
    left: 20,
    right: 20,
    zIndex: 9999,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
    zIndex: 1001,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 28,
    width: width * 0.9,
    maxWidth: 600,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    zIndex: 1002,
  },
  modalHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE6E9',
  },
  modalHeader: {
    fontSize: 28,
    fontWeight: '800',
    color: '#333333',
    letterSpacing: 0.5,
  },
  detailsGrid: {
    flexDirection: 'column',
    marginBottom: 28,
    gap: 16,
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  detailsItem: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  detailsLabel: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 6,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailsValue: {
    fontSize: 18,
    color: '#333333',
    fontWeight: '700',
  },
  detailsActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 36,
    gap: 20,
  },
  dateInputContainer: {
    marginBottom: 20,
  },
  dateInputLabel: {
    fontSize: 16,
    color: '#666666',
    marginBottom: 10,
    fontWeight: '600',
  },
  modalInputContainer: {
    marginBottom: 24,
  },
  modalInputLabel: {
    fontSize: 16,
    color: '#666666',
    marginBottom: 8,
    fontWeight: '600',
  },
  modalInput: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 18,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#DFE6E9',
    color: '#333333',
  },
  datePicker: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  datePickerText: {
    fontSize: 16,
    color: '#333333',
    fontWeight: '600',
  },
  percentageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  percentageLabel: {
    fontSize: 16,
    color: '#666666',
    fontWeight: '600',
    marginLeft: 8,
  },
  percentageInput: {
    flex: 1,
    fontSize: 16,
    color: '#333333',
    padding: 0,
    margin: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 16,
  },
  modalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  saveButton: {
    backgroundColor: '#FFB74D',
  },
  cancelButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  cancelButtonText: {
    color: '#666666',
    fontWeight: '600',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  deleteModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  deleteModalTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#333333',
    marginLeft: 14,
  },
  deleteModalText: {
    fontSize: 20,
    color: '#333333',
    textAlign: 'center',
    marginBottom: 14,
    fontWeight: '600',
  },
  deleteModalSubtext: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 32,
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  financialMetricsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
    gap: 16,
  },
  metricCard: {
    flex: 1,
    minWidth: width * 0.4,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  metricLabel: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 8,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  metricValue: {
    fontSize: 20,
    color: '#333333',
    fontWeight: '700',
  },
  availableMoney: {
    color: '#FFB74D',
  },
  savingsPercentage: {
    color: '#FFA726',
  },
  savingsInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: '#DFE6E9',
    position: 'relative',
  },
  savingsInput: {
    flex: 1,
    fontSize: 24,
    color: '#333333',
    fontWeight: '700',
    textAlign: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#DFE6E9',
    marginRight: 12,
  },
  savingsInputLabel: {
    fontSize: 24,
    color: '#666666',
    fontWeight: '700',
    position: 'absolute',
    right: 30,
  },
  savingsDescription: {
    fontSize: 14,
    color: '#666666',
    marginTop: 8,
    fontStyle: 'italic',
  },
});

export default styles;
