import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    padding: 16,
    paddingTop: 0,
  },
  header: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D3436',
    marginBottom: 16,
    textAlign: 'center',
  },
  goalItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  goalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  goalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  warningIcon: {
    marginRight: 8,
  },
  goalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#2D3436',
    flexWrap: 'nowrap',
    numberOfLines: 1,
    flex: 1,
  },
  goalAmount: {
    fontSize: 18,
    fontWeight: '600',
    color: '#00B894',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  progressContainer: {
    height: 8,
    backgroundColor: '#DFE6E9',
    borderRadius: 4,
    marginBottom: 8,
    position: 'relative',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#00B894',
    borderRadius: 4,
  },
  progressText: {
    position: 'absolute',
    right: 0,
    top: -20,
    fontSize: 14,
    color: '#7F8C8D',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  goalDeadlineContainer: {
    marginTop: 8,
  },
  goalDeadline: {
    fontSize: 14,
    color: '#7F8C8D',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  deadlineRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  progressPercentage: {
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  addButton: {
    backgroundColor: '#00B894',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 500,
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#DFE6E9',
  },
  modalHeader: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D3436',
  },
  closeButton: {
    padding: 5,
  },
  modalContent: {
    marginBottom: 20,
  },
  modalInputContainer: {
    marginBottom: 15,
  },
  modalInputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3436',
    marginBottom: 8,
  },
  modalInput: {
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#2D3436',
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  savingsDescription: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 4,
    flexWrap: 'nowrap',
  },
  modalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 8,
    paddingTop: 0,
    borderTopWidth: 0,
  },
  modalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 8,
    gap: 8,
  },
  saveButton: {
    backgroundColor: '#00B894',
  },
  cancelButton: {
    backgroundColor: '#E74C3C',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  statusContainer: {
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusIcon: {
    marginRight: 8,
  },
  statusTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  statusText: {
    fontSize: 16,
    lineHeight: 24,
  },
  financialMetricsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  metricCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    width: '48%',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 80,
  },
  metricLabel: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 8,
    flexWrap: 'nowrap',
  },
  metricValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2D3436',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  metricSubValue: {
    fontSize: 12,
    fontWeight: '400',
    color: '#7F8C8D',
    marginTop: 4,
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  availableMoney: {
    color: '#00B894',
  },
  listWrapper: {
    flex: 1,
  },
  listContainer: {
    paddingBottom: 16,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#7F8C8D',
    textAlign: 'center',
    marginTop: 16,
  },
  alertContainer: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    zIndex: 1000,
    alignItems: 'center',
  },
  alertContainerInModal: {
    position: 'absolute',
    top: 20,
    left: 0,
    right: 0,
    zIndex: 999999,
    alignItems: 'center',
  },
  detailsGrid: {
    marginBottom: 24,
  },
  detailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  detailsItem: {
    flex: 1,
    marginRight: 16,
  },
  detailsLabel: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 8,
  },
  detailsValue: {
    fontSize: 16,
    color: '#2D3436',
    fontWeight: '600',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  detailsSubtext: {
    fontSize: 14,
    color: '#00B894',
    marginTop: 4,
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  detailsActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 12,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    gap: 8,
  },
  editButton: {
    backgroundColor: '#00B894',
  },
  deleteButton: {
    backgroundColor: '#E74C3C',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  deleteModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  deleteModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2D3436',
    marginLeft: 8,
  },
  deleteModalText: {
    fontSize: 18,
    color: '#2D3436',
    textAlign: 'center',
    marginBottom: 8,
  },
  deleteModalSubtext: {
    fontSize: 14,
    color: '#7F8C8D',
    textAlign: 'center',
    marginBottom: 24,
  },
  deleteModalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  deleteModalButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    gap: 16,
  },
  deleteModalButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
  },
  deleteModalCancelButton: {
    backgroundColor: '#DFE6E9',
  },
  deleteModalConfirmButton: {
    backgroundColor: '#E74C3C',
  },
  deleteModalButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  deleteModalCancelButtonText: {
    color: '#2D3436',
  },
  savingsTypeContainer: {
    flexDirection: 'row',
    backgroundColor: '#F8F9FA',
    borderRadius: 8,
    padding: 4,
    borderWidth: 1,
    borderColor: '#DFE6E9',
  },
  savingsTypeButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  savingsTypeButtonActive: {
    backgroundColor: '#00B894',
  },
  savingsTypeButtonText: {
    fontSize: 16,
    color: '#7F8C8D',
    fontWeight: '500',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  savingsTypeButtonTextActive: {
    color: '#FFFFFF',
    flexWrap: 'nowrap',
    numberOfLines: 1,
  },
  scenariosContainer: {
    marginTop: 20,
    marginBottom: 15,
  },
  scenariosHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3436',
    flex: 1,
  },
  scenariosContent: {
    gap: 12,
  },
  scenarioCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 4,
  },
  recommendedScenarioCard: {
    borderLeftColor: '#00B894',
    backgroundColor: '#F0FDF4',
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  possibleScenarioCard: {
    borderLeftColor: '#3B82F6',
    backgroundColor: '#F0F9FF',
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  impossibleScenarioCard: {
    borderLeftColor: '#EF4444',
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  currentScenarioCard: {
    borderLeftColor: '#8B5CF6',
    backgroundColor: '#FAF5FF',
    borderWidth: 1,
    borderColor: '#DDD6FE',
  },
  scenarioHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  scenarioIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recommendedIcon: {
    backgroundColor: '#00B894',
  },
  possibleIcon: {
    backgroundColor: '#3B82F6',
  },
  impossibleIcon: {
    backgroundColor: '#EF4444',
  },
  currentIcon: {
    backgroundColor: '#8B5CF6',
  },
  scenarioTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3436',
    flex: 1,
  },
  scenarioDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    marginBottom: 4,
  },
  scenarioSubDescription: {
    fontSize: 13,
    color: '#9CA3AF',
    lineHeight: 18,
    fontStyle: 'italic',
  },
  scenarioRemainingValue: {
    fontSize: 13,
    color: '#00B894',
    fontWeight: '600',
    marginTop: 8,
    backgroundColor: '#F0FDF4',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  recommendedBadge: {
    backgroundColor: '#00B894',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  recommendedBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  expenseDetailsContainer: {
    marginTop: 6,
    paddingLeft: 10,
  },
  expenseDetailItem: {
    fontSize: 11,
    color: '#636E72',
    lineHeight: 16,
  },
  headerActionButton: {
    padding: 5,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  backIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 132, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 132, 0, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
